version: '2'  # Docker Compose version v2.27.1

name: task5  # Имя проекта

services:  # Definition of services to be run in containers
  ros-noetic-master:  # Service name
    build:  # Instructions for building the image
      context: ../  # Build context, the base directory for building
      dockerfile: ./docker/Dockerfile  # Path to the Dockerfile relative to the context
    working_dir: /home/dmitriy/task5  # Working directory inside the container
    volumes:  # Volumes attached to the container
      - /home/dmitriy/task5  # Mounting the project folder from the host to the container
    env_file:  # Environment variables file
      - ./.env  # Path to the environment variables file
    tty: true  # Enable TTY mode, allowing the use of an interactive terminal in the container

