version: '4'
services:
  Kont1:
    image: rosgazebo
    volumes:
      - $HOME/task5:/home/dmitriy/task5
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: sh -c "bash scripts/script.sh" #скрипт выполняется, но контейнера нет.
  Kont2:
    image: rosgazebo
    volumes:
      - $HOME/task5:/home/dmitriy/task5
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: sh -c "bash scripts/script2.sh"